# Use root/example as user/password credentials
version: "3.1"

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./database/data:/data/db
    networks:
      - test_setel

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    networks:
      - test_setel

  redis:
    image: redis:6.0.9-alpine
    restart: always
    ports:
      - 6379:6379
    networks:
      - test_setel

  order-app:
    build: ./order-app
    restart: always
    ports:
      - 4000:4000
    volumes:
      - ./order-app/:/app/
      - /app/node_modules/
    depends_on:
      - mongo
      - redis
    networks:
      - test_setel

  payment-app:
    build: ./payment-app
    restart: always
    ports:
      - 5000:5000
    volumes:
      - ./payment-app/:/app/
      - /app/node_modules/
    networks:
      - test_setel

  client-app:
    build: ./order-react
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./order-react/:/app/
      - /app/node_modules/
    networks:
      - test_setel

networks:
  test_setel:
